namespace HelloForms;

// GENERATED by the designer. This is the other half of the partial class.
// Everything you do in the designer becomes code in InitializeComponent().
partial class MainForm
{
    private System.ComponentModel.IContainer components = null;

    // The designer adds a private field per control here:
    private System.Windows.Forms.Button btnOk;
    private System.Windows.Forms.Label lblTitle;

    protected override void Dispose(bool disposing)
    {
        if (disposing && components != null) components.Dispose();
        base.Dispose(disposing);
    }

    private void InitializeComponent()
    {
        this.btnOk = new System.Windows.Forms.Button();
        this.lblTitle = new System.Windows.Forms.Label();
        this.SuspendLayout();   // batch layout changes for performance

        // btnOk — each Properties-window change is one line here
        this.btnOk.Location = new System.Drawing.Point(20, 60);
        this.btnOk.Name = "btnOk";
        this.btnOk.Text = "OK";
        this.btnOk.Click += new System.EventHandler(this.btnOk_Click); // event wiring

        // lblTitle
        this.lblTitle.AutoSize = true;
        this.lblTitle.Location = new System.Drawing.Point(20, 20);
        this.lblTitle.Text = "Title";

        // MainForm
        this.ClientSize = new System.Drawing.Size(400, 200);
        this.Controls.Add(this.btnOk);
        this.Controls.Add(this.lblTitle);
        this.Name = "MainForm";
        this.Text = "Designer Demo";
        this.ResumeLayout(false);
        this.PerformLayout();
    }
}
